import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Provider from '@/Provider/Provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <Provider>
          <main className='container mx-auto h-full max-w-7xl pt-12'>
            {children}
          </main>
        </Provider>{' '}
      </body>
    </html>
  );
}
